name: "Dependency Review"
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}-deps-review
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    permissions:
      contents: read # for actions/checkout
      pull-requests: write # for actions/dependency-review-action to post comments
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Dependency Review"
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
        with:
          config-file: "nginxinc/k8s-common/dependency-review-config.yml@main"
